-- MySQL Script generated by MySQL Workbench
-- Tue Jun  4 17:47:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_jpu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_jpu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_jpu` DEFAULT CHARACTER SET utf8 ;
USE `bd_jpu` ;

-- -----------------------------------------------------
-- Table `bd_jpu`.`familiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jpu`.`familiar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `apellidos` VARCHAR(150) NULL,
  `fec_nac` DATE NULL,
  `edad` INT NULL,
  `sexo` TINYINT NULL,
  `labor` VARCHAR(100) NULL,
  `ocupacion` VARCHAR(100) NULL,
  `dependencia` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_jpu`.`laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jpu`.`laboral` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresa` VARCHAR(100) NULL,
  `cargo` VARCHAR(45) NULL,
  `fec_ingreso` DATE NULL,
  `fec_cese` DATE NULL,
  `sueldo` DECIMAL(4,2) NULL,
  `jefe_inmed` VARCHAR(100) NULL,
  `motivo` VARCHAR(100) NULL,
  `situacion_actual` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_jpu`.`estudios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jpu`.`estudios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `secundaria` VARCHAR(45) NULL,
  `tecnico` VARCHAR(45) NULL,
  `universitario` VARCHAR(45) NULL,
  `postgrado` VARCHAR(45) NULL,
  `idiomas` VARCHAR(45) NULL,
  `otros` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_jpu`.`ubigeo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jpu`.`ubigeo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(150) NULL,
  `distrito` VARCHAR(150) NULL,
  `provincia` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_jpu`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jpu`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ape_usu` VARCHAR(200) NULL,
  `nom_usu` VARCHAR(60) NULL,
  `fec_nac` DATE NULL,
  `ciudad_nac` VARCHAR(100) NULL,
  `edad` INT NULL,
  `dni` INT NOT NULL,
  `sexo` TINYINT NULL,
  `discapacidad` TINYINT NULL,
  `email` VARCHAR(150) NULL,
  `celular` INT NULL,
  `familiar_id` INT NOT NULL,
  `laboral_id` INT NOT NULL,
  `estudios_id` INT NOT NULL,
  `ubigeo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuario_familiar`
    FOREIGN KEY (`familiar_id`)
    REFERENCES `bd_jpu`.`familiar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_laboral1`
    FOREIGN KEY (`laboral_id`)
    REFERENCES `bd_jpu`.`laboral` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_estudios1`
    FOREIGN KEY (`estudios_id`)
    REFERENCES `bd_jpu`.`estudios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_ubigeo1`
    FOREIGN KEY (`ubigeo_id`)
    REFERENCES `bd_jpu`.`ubigeo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_familiar_idx` ON `bd_jpu`.`usuario` (`familiar_id` ASC) VISIBLE;

CREATE INDEX `fk_usuario_laboral1_idx` ON `bd_jpu`.`usuario` (`laboral_id` ASC) VISIBLE;

CREATE INDEX `fk_usuario_estudios1_idx` ON `bd_jpu`.`usuario` (`estudios_id` ASC) VISIBLE;

CREATE INDEX `fk_usuario_ubigeo1_idx` ON `bd_jpu`.`usuario` (`ubigeo_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bd_jpu`.`recursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_jpu`.`recursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gerencia` VARCHAR(100) NULL,
  `area` VARCHAR(100) NULL,
  `puesto` VARCHAR(100) NULL,
  `fec_inicio` DATE NULL,
  `reingreso` TINYINT NULL,
  `salario` DECIMAL(4,2) NULL,
  `observaciones` VARCHAR(250) NULL,
  `bonos` VARCHAR(45) NULL,
  `recursoscol` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_recursos_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bd_jpu`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_recursos_usuario1_idx` ON `bd_jpu`.`recursos` (`usuario_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
